

export const AUTH_ERROR_CODES = {
    // 1. 로그인 및 기본 인증
    UNAUTHORIZED: "UNAUTHORIZED",
    LOGIN_FAILED: "LOGIN_FAILED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    LOGIN_EMAIL_NOT_FOUND: "LOGIN_EMAIL_NOT_FOUND",
    EMAIL_DUPLICATE: "EMAIL_DUPLICATE",
    INVALID_TOKEN: "INVALID_TOKEN",
    EXPIRED_TOKEN: "EXPIRED_TOKEN",
    ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
    WITHDRAWN_ACCOUNT: "WITHDRAWN_ACCOUNT",
    TOO_MANY_ATTEMPTS: "TOO_MANY_LOGIN_ATTEMPTS",

    // 2. 계정 연동 및 비밀번호
    PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
    ALREADY_LINKED_LOCAL: "ALREADY_LINKED_LOCAL",
    SOCIAL_LINK_FAILED: "SOCIAL_LINK_FAILED",
    PHONE_DUPLICATE: "PHONE_DUPLICATE",
    SOCIAL_USER_LOGIN_ATTEMPT: "SOCIAL_USER_LOGIN_ATTEMPT",

    // 3. 인증번호 관련
    USER_INFO_MISMATCH: "USER_INFORMATION_MISMATCH",
    VERIFY_CODE_MISMATCH: "VERIFICATION_CODE_MISMATCH",
    VERIFY_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
    MAIL_SEND_FAILED: "MAIL_SEND_FAILED",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",

    // 4. 회원 탈퇴 관련
    INVALID_CONFIRM_TEXT: "INVALID_CONFIRM_TEXT",
    WITHDRAW_PW_MISMATCH: "WITHDRAW_PASSWORD_MISMATCH",
    RESTORE_TOKEN_INVALID: "RESTORE_TOKEN_INVALID",

    // 5. 계정 복구 관련
    RECOVERY_NOT_FOUND: "RECOVERY_NOT_FOUND",
    INVALID_AUTH_CODE: "INVALID_AUTH_CODE",
    PHONE_ALREADY_ACTIVE: "PHONE_ALREADY_ACTIVE",
    SOCIAL_RECOVERY_CONFLICT: "SOCIAL_RECOVERY_PHONE_CONFLICT",
    ALREADY_LINKED_SOCIAL: "ALREADY_LINKED_SOCIAL",
    INVALID_USER_FORMAT: "INVALID_USER_DATA_FORMAT"
};