# application-aws.properties
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.s3.bucket=${AWS_BUCKET_NAME}
cloud.aws.region.static=ap-northeast-2cloud.aws.stack.auto=false