spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

spring.cloud.aws.s3.bucket=${S3_BUCKET_NAME}
spring.cloud.aws.region.static=${S3_REGION}

spring.cloud.aws.stack.auto=false